language: php
php:
- '7.1'
sudo: required
dist: trusty
group: deprecated-2017Q4
before_script:
- cp .env.travis .env
- composer install --prefer-dist --no-interaction
- php artisan cache:clear
- php artisan key:generate
- nvm install 7.7.1
- npm install -s npm@latest -g
- npm install -s -g jshint
- npm install -s
script:
- php artisan migrate
- npm run production
before_deploy:
- rm .env
- rm .env.travis
- rm .env.example
- touch .env
- export ARTIFACT_PRE=$(echo $TRAVIS_REPO_SLUG | sed  s_^.*/__)
- export ARTIFACT_NAME=${ARTIFACT_PRE}-${TRAVIS_BRANCH}-$(
  echo ${TRAVIS_COMMIT} | cut -b 1-8
  )-$(
  date -u +%FT%T%Z
  ).zip
- export ELASTIC_BEANSTALK_LABEL=$(echo $ARTIFACT_NAME | sed s_.zip__)
- zip $ARTIFACT_NAME -q -r * .[^.]*
- ls -la $ARTIFACT_NAME
branches:
  only:
  - master
deploy:
- provider: elasticbeanstalk
  skip_cleanup: true
  zip_file: "$ARTIFACT_NAME"
  access_key_id:
    secure: "kkZ8rH18mVMdsYk9rKFbHecJw3BiRpy9bEBDSVeQKDvDOR0/Lrtg2tDHY9tdmJdleDKdcO0bt+iBkPZQ4b1PxCLurALBgIe68Gk2othl13WPXmjiHL3PUX4t3ho5yAlnrXxX0QBkYBadjqrG2jW4R5kpK/ce7ekZ7QW0qOH/xXfn3zsSytwWdOB2HbN1124+FMO1xZewAl9bUYAH2Dpww3i2oEF8jhUVSr1NO7GABSFUenpkhUuj0USTwOQRYCSm6zNMWAzQVrVlLE/nXZ9je/V714ImKqRIDYyI4GHmcLdj3b+X8HXrvXzhZhy22Z1+TovbwHOMGLscL00zvBk7LEEgYjOrPZ8mTUBzHDBsR5/IdT8TaGKVw87Rrrf7Urq3ejmqbp8M5RFTirea2KmIijymKwAPM011GmuQ7CUX4/VSWyLQjj82+JDT5/N1rFiwRf/bURjLYd9bu6KsIq8N/zadtAIbVF41Wtvojh0kRFXOkvVv92ZmLzi5Hgxit21Whrikd3b0WhJARmAWyGd8ndqgo1JowAbNnCbcJTYB847vFR9ZIhOKtyZ0iQzt92cbZsJOSUjm1Slwng1rgKks2H3IDjGyjjMtYpO67c+HJWbVJglJ/JmMrsbnsv5reyTc7ZmtteheNhgrBZMnxd2fSdF9wf0yk/GSjYh+YH/e7KM="
  secret_access_key:
    secure: "a5Q8fhLGaog+oXEVSNN0iATYeV3jcafx8dvVZXzH8oeaLrZiaVGtN1M0rbtuJgb5WCHmdDWMTMTw8zeMdHp7vFHU7z+1h70NR2V3bnjXsJopsn5JvHTDNHkd6HYZuJw1pvOhEv5y8wXoJ0dgwN45+4+9BD/lgPZapRTkaE1p8oeWHGpUbwmrCCdz6pzMAhVJe+5Ina2sGng4FAI5CbMCGQkf8yUTY0r674yq0/V1H/1g0KKeF34nUQDnYXQVTkJAeedoiTMUzbhoZ58U5G77Qk3JwvqnssUv8twigdlmukH+CFeEGNka0Nt5gH+zOQzoRbtZzWQtbwRv1cMU5wgrVjftW8xZhS8Ld6VtGv5bA6D/a7OggYRxs3MCv1BRX/svmxhkmT50EAaZCxTLeBvpQtXPMGDLaX9DaTQ2ueROweZQ2K3X9FUTH95kyhoEFzTx61v/tYDZUMEzLsaDkE6Erx4DObmJf7fNVec2Cg84e5SBEn8ucnvOI4a9KrsAbbKa9zFB6nr4b72nc/63U1PG/6MOTCQ/oxYakykJKPMCB87pZU3JcGwhXEwbZn4IGxeUT/6D5BRlnjka8P/ugutW9UpR0E561dHsE0D1lXCL7ct1oiuCk9Y8hwiWl6vR8toJKt+XG2gw4VOq3Kkj59fWZ8QVgFWBpHGmNyxehVaVdbo="
  region: eu-central-1c
  app: test
  env: Test-env
  bucket_name: elasticbeanstalk-eu-central-1-935769189383
  on:
    branch: master
